# Generated by Django 5.1.1 on 2024-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_blog_author_blog_date_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=7)),
                ('color_image', models.URLField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
