# Generated by Django 5.1.1 on 2024-10-30 10:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('properties', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Properties')),
                ('range', models.JSONField(blank=True, default=list)),
                ('technical_data', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='color_image',
            field=models.ImageField(upload_to='color_images/'),
        ),
    ]
